# Check tag against debian changelog version
tag-debian-version-check:
  image: docker.ops.iszn.cz/baseimage/debian-java8-jdk-ci:$DIST
  stage: test
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+/
  script:
    - export TAG_VERSION=$(git describe --exact-match --tags | sed "s/^.//")
    - export DEB_VERSION=$(dpkg-parsechangelog | grep "Version:" | cut -d " " -f 2)
    - echo "Version from tag:" ${TAG_VERSION}
    - echo "Version from debian changelog:" ${DEB_VERSION}
    - test "${TAG_VERSION}" == "${DEB_VERSION}"
