# vim: ft=dockerfile
FROM docker.ops.iszn.cz/upstream/python:3.9-slim 

WORKDIR /app

COPY tests/integrity ./tests

RUN apt-get update && apt-get install --yes curl && \
    pip3 install --no-cache-dir -r tests/requirements.txt



